apiVersion: v1
kind: Pod
metadata:
  name: todo-app
spec:
  containers:
    - name: todo-app
      image: crazywebdev/todo-app-argocd: c302a2553d95ae49463678b0a17e802020770342
      ports:
      - containerPort: 80
