apiVersion: v1
kind: Pod
metadata:
  name: todo-app
spec:
  containers:
    - name: todo-app
      image: crazywebdev/todo-app-argocd:83858d3a7949772635ca7c97b47e01d3bc45d12e
      ports:
      - containerPort: 80
